import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";
import Logo from './svg/logo.svg'
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rick and Morthy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-auto max-w-5xl">
        <header className="flex justify-between h-60 items-center border-b-2">
          <div>
            <Image src={Logo} alt="Logotipe" />
          </div>
          <nav className="flex justify-between w-80">
            <Link href="/Characters">Characters</Link>
            <Link href="/Episodes">Episodes</Link>
            <Link href="/Locations">Locations</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
